# SurfPatch 3.0.11 Beta
# contact Dreeam on QQ2682173972
# for help with this plugin

#Messages to send the player when they try to place illegal blocks
IllegalBlock-Place:
  Enabled: true
  Bedrock: '&6&l[&b&lSurf&6&l]&6 &6That block is not allowed'
  Barrier: '&6&l[&b&lSurf&6&l]&6 &6That block is not allowed'
  End_Portal_Frame: '&6&l[&b&lSurf&6&l]&6 &6That block is not allowed'
  Mob_Spawner: '&6&l[&b&lSurf&6&l]&6 &6That block is not allowed'
#ChunkBan skull limit tile entity limit and prevent message
ChunkBan:
  Enabled: true
  Prevent-Message: '&6&l[&b&lSurf&6&l]&6 &6ChunkBan has been disabled due to an exploit (^:'
  TileEntity-Max: 500
  Skull-Max: 100
#Nether top and bottom layers
Nether:
  Enabled: true
  Top-Layer: 127
  Top-message: '&6&l[&b&lSurf&6&l]&6 &6The nether top has been disabled due to lag'
  Bottom-Layer: 0
  Bottom-message: '&6&l[&b&lSurf&6&l]&6 &6The nether bottom has been disabled due to lag'
  top-bottom-do-damage: true
#Misc config shit
#Message to send when a player tries to use a 32k or strength 255
IllegalDamage:
  Message: "&6&l[&b&lSurf&6&l]&6&6 How did you even get a 32k out to begin with"
#Player attempts to use or drink an illegal potion or use an illegal tipped arrow
IllegalPotion:
  Message: "&6&l[&b&lSurf&6&l]&6&6 Sorry those are patched"
UnbookBan:
  Message: "&6&l[&b&lSurf&6&l]&6&6 You have been unbookbanned"
#Message for /discord use & for colors
#make sure to add the permission l2x9core.command.discord
Discord: "&6[&b&lSurf&6&l] Join us on discord at &c"
#TP on an entity exploit prevent message
tp.prevent:
  message: "&6&l[&b&lSurf&6&l]&6 &6Patched"
#World name for the /world command and the fortress dat deleter
World-name: "world"
#AntiIllegal check toggles
#Only enable ChunkLoad of you have a massive problem with illegals on your server
Antiillegal:
  Block-Place-Enabled: true
  ChunkLoad-Enabled: false
  HopperTransfer-Enabled: true
  InventoryClose-Enabled: true
  InventoryOpen-Enabled: true
  PlayerHotbarMove-Enabled: true
  ItemPickup: true
  Check-Illegal-Damage: true
  Illegal-Items-List:
    - "BEDROCK"
    - "COMMAND_REPEATING"
    - "COMMAND_MINECART"
    - "COMMAND_CHAIN"
    - "COMMAND"
    - "ENDER_PORTAL_FRAME"
    - "PORTAL"
    - "STRUCTURE_BLOCK"
    - "STRUCTURE_VOID"

#TODO
#FillInBedrockFloor: false
#FillInBedrockRoof: false
