name: SurfPatch
version: 3.0.12
main: org.l2x9.l2x9core.Main
authors: [ 254n_m, Leeewith3Es, Dreeam ]
description:  ${project.description}
softdepend:
  - SalC1Dupe
commands:
  surf:
    description: main command of this plugin
  discord:
    description: get discord link
