name: LeeesExploitFixer
version: 3.0.5
main: org.l2x9.l2x9core.Main
authors: [ 254n_m, Leeewith3Es, Dreeam ]
description:  ${project.description}
website: https://www.xera.ca
softdepend:
  - SalC1Dupe
commands:
  crash:
    description: e
  uuid:
    description: e
  lef:
    description: e
  discord:
    description: e
  world:
    description: e
  toggleconnectionmessages:
    description: Toggles on / off connection messages for the sender of the command
    aliases:
      - tc
      - toggleconnection
