name: SurfPatch
version: 3.0.7
main: org.l2x9.l2x9core.Main
authors: [ 254n_m, Leeewith3Es, Dreeam ]
description:  ${project.description}
softdepend:
  - SalC1Dupe
commands:
  crash:
    description: e
  uuid:
    description: e
  lef:
    description: e
  discord:
    description: e
  world:
    description: e
